---
title: "Presidential Elections"
author: "Matthew Marcum"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r,  include=FALSE}
library(socviz)
library(gapminder)
library(tidyverse)
library(here)
library(dplyr)
library(modelr)
library(broom)
library(GGally)
library(readxl)
library(downloadthis)
```

Presidential Election Results By State

```{r}
election2012 <- read.csv("https://raw.githubusercontent.com/mg-marcum/Gubernatorial-Elections/main/federalelections2012.csv")
election2012$Winner <- with(election2012, ifelse(Democrat > Republican, "D", "R"))
election2016 <- read.csv("https://raw.githubusercontent.com/mg-marcum/Gubernatorial-Elections/main/federalelections2016.csv")
election2016$Winner <- with(election2012, ifelse(Democrat > Republican, "D", "R"))
election2020 <- read.csv("https://raw.githubusercontent.com/mg-marcum/Gubernatorial-Elections/main/2020federalelections.csv")
election2020$Winner <- with(election2012, ifelse(Democrat > Republican, "D", "R"))
election_combined_2012.2016 <- full_join(election2012, election2016, by = "STATE")
election_combined_and2020a <- full_join(election_combined_2012.2016, election2020, by = "STATE")
election_combined_and2020 <- subset(election_combined_and2020a, STATE != "DC")
election_combined <- election_combined_and2020 %>% rename(Democrat2012 = Democrat.x, Republican2012 = Republican.x, Other2012 = Other.x, Winner2012 = Winner.x, Democrat2016 = Democrat.y, Republican2016 = Republican.y, Other2016 = Other.y, Winner2016 = Winner.y, Democrat2020 = Democrat, Republican2020 = Republican, Other2020 = Other, Winner2020 = Winner)
```

Groupings

```{r}
election_combined$Political_Favorabilty <- ifelse(rowSums(election_combined == "D") == 3, "Democrat", ifelse(rowSums(election_combined == "R") == 3, "Republican", "Swing"))
ElectionTiming <- read.csv("https://raw.githubusercontent.com/mg-marcum/Gubernatorial-Elections/main/ElectionTiming.csv")
election_groups <- full_join(election_combined, ElectionTiming, by = "STATE")
election_groups %>% download_this(output_name = "Presidential Elections and State Groupings", output_extension = ".xlsx", button_label = "Download as XLSX", button_type = "warning", has_icon = TRUE, icon = "fa fa-save")
```